### ISSUE TITLE
We need a name for the game

### ISSUE THREAD

**Issue by spleen387** [maritimegamelab/ProjectPurpleClockYellow#1]
I'm already getting sick of "Island Game" (hence projectpurpleclockyellow)
anyone got any ideas?

**Comment by AncientPear** [comment]
I would decide the Name in the End , cause then the outcome is the besz (at least in my opinion)

**Comment by spleen387** [comment]
Good point!
First issue solved!

**Comment by AncientPear** [comment]
Second issue !

OK , it is clear , pixelart , but what KIND of pixelart ?
